[[redirects]]
  from = "/*"
  to = "https://d33wubrfki0l68.cloudfront.net"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
